### ISSUE TITLE
BadZipfile error raised with zipped files.

### ISSUE THREAD

**Issue by tboser** [codalab/codalab-competitions#2353]
Competition 19801.

Submitted zipped sample submission which raised a BadZipfile error. Ingestion output log shows a complete run of the injestion file which means the submission must have been unzipped (it imports model.py from the submission file). When the prediction/scoring is done it raises the error.

Traceback (most recent call last):
  File "/worker/worker.py", line 297, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 158, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 158, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 117, in get_bundle
    with ZipFile(bundle_file.file, 'r') as z:
  File "/usr/local/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

Browser: Chrome
Same error has occurred for at least two submissions.

**Comment by ckcollab** [comment]
It looks like this problem is intermittent? Maybe due to a specific worker? Still digging into it...

**Comment by ckcollab** [comment]
Hopefully fixed by bumping azure upload limit by tweaking version header

**Comment by zhengying-liu** [comment]
I got the same error on the [AutoDL staging server](http://134.158.74.63/competitions/72#participate):
<img width="1252" alt="screen shot 2018-11-26 at 23 36 32" src="https://user-images.githubusercontent.com/20074659/49047115-bb272400-f1d6-11e8-9aea-0ef345378a2d.png">

I thought this was due to the fact that there was no metadata file in the zip. But another submission didn't have it either but worked fine...

**Comment by AbdoKamel** [comment]
I have seen this issue recently (over the past couple of weeks) in this competition: https://competitions.codalab.org/competitions/22230

**Comment by zhengying-liu** [comment]
I think this issue still exists and has been observed on several new competitions.

**Comment by mlopezantequera** [comment]
We are experiencing the same issue in a self-hosted instance. Any clues or at least workarounds for the users?

**Comment by konbick** [comment]
This problem still remains... :
![2021-01-11 12_05_04-CodaLab - Competition](https://user-images.githubusercontent.com/26271588/104173384-fa8c4b00-5405-11eb-85bf-c7fb6314855b.png)
The funny thing is, the files that now fail are the same that worked last December... any help?

**Comment by zhengying-liu** [comment]
@ckcollab @Tthomas63 
Is it possible that this error is due to the fact that the ZIP file is being unzipped while it is not yet fully downloaded? So only the first few bytes are used for unzipping, which causes the error. Maybe we need to have a mechanism to guarantee that files are only being unzipped when it's complete?

**Comment by konbick** [comment]
@zhengying-liu thanks for the quick answer! This might be a good hint as I am right now facing the 'no psace left on device' problem. So previously it might have just stopped downloading the whole file because it was full already? Will continue to investigate.

**Comment by konbick** [comment]
@zhengying-liu Just wanted to give feedback that in my case the problem with BadZipfile error was caused by insufficient storage on the worker. Freeing up some space solved the problem. Maybe that helps.

**Comment by zhengying-liu** [comment]
> @zhengying-liu Just wanted to give feedback that in my case the problem with BadZipfile error was caused by insufficient storage on the worker. Freeing up some space solved the problem. Maybe that helps.

Ok great! It's good to know. Thank you for the feedback!

**Comment by bomb2peng** [comment]
I also had this Badzip error.
In my case, when the uploaded reference data is a zip of sub-zips, I had this error. When the reference data is changed to a zip of unzipped subfolders, the error is gone.
Hope this information is helpful.

**Comment by skyqwe123** [comment]
Challenge and Workshop on Localized and Detailed Understanding of Human Actions in Videos

**Comment by skyqwe123** [comment]
@madclam  Excuse me ， Where can I download the dataset？    ICCV DeeperAction Challenge - FineAction Track on Temporal Action Localization

**Comment by mlopezantequera** [comment]
Getting this error in the public servers as well. I've confirmed that the zip file is not corrupt and that it can be unzipped using "unzip". Have tested from different computers compressing the file with different programs, always getting the same error

**Comment by Didayolo** [comment]
I've merged this issue with other error messages to be improved.

**Comment by rafariva** [comment]
Having the same error with BadZipFile. try different browser, zips file, OS. the competitions was working fine, then, its start with this problem.
