### ISSUE TITLE
An error occurred while evaluating in test-dev COCO Detection Challenge (Segmentation Mask) 

### ISSUE THREAD

**Issue by fh2019ustc** [codalab/codalab-competitions#3260]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
File "/tmp/codalab/tmpBikn8N/run/program/run.py", line 36, in
from pycocotools.coco import COCO
ModuleNotFoundError: No module named 'pycocotools'

confusing...

**Comment by TempleX98** [comment]
we met the same bug while evaluating COCO test-dev bbox

**Comment by Didayolo** [comment]
Hello,

I think it is not due to the version of the server, but to the recently updated version of the default docker image used to evaluate submissions (see https://groups.google.com/g/codalab-competitions/c/byvq0n7Vc2k).

 If no competition docker image is set in a competition, then the default image is used so this change can have an effect.

The new default image is `codalab/codalab-legacy:py39`.

I have to check but I think the old one is `codalab/codalab-legacy:1.0.1`. So, setting `codalab/codalab-legacy:1.0.1` as the competition docker image should solve the problem. 

**Please give me the URL to the competition and I'll make this change.**

**Comment by TempleX98** [comment]
> 

https://codalab.lisn.upsaclay.fr/competitions/7384#learn_the_details

**Comment by Didayolo** [comment]
Let's treat this problem in the following issue: #3263

**Comment by fh2019ustc** [comment]
https://codalab.lisn.upsaclay.fr/competitions/7383#participate-submit_results

**Comment by fh2019ustc** [comment]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpK8VYak/run/program/run.py", line 36, in 
    from pycocotools.coco import COCO
ModuleNotFoundError: No module named 'pycocotools'

Looks like the bug still exists for https://codalab.lisn.upsaclay.fr/competitions/7383

**Comment by fh2019ustc** [comment]
![image](https://user-images.githubusercontent.com/50725551/192734016-30ccdac0-3d5d-4a58-ab99-42df0eb56197.png)

**Comment by fh2019ustc** [comment]
Now  I  can conduct the evaluation. Thanks~!
